travis:
  secure:
    BINSTAR_TOKEN: qrZg9xmka5BzOuHu50P1DDbeXN8cVQG3q2sct33T/Y3KZ9b9i4FYKcAFskBqQZwrfxfypLuCGaB4hVPTdr7rlE4RCey7IsS/542rQKTUZqTURC9DhOQwDsjFqVxpxTmJRodF1rziiS8I3wAMSXmhb8vPyPBaZfV3QZEupLhigGbKo2eL6Ic+mHh0jwoTqnYBMEdzlyPeYzvWsQjkLIA/INBRP/hfT6TotM5+2pw2Yh+9VNoa0K6F39Jpd2Xi9pP1pEBaXdSWGNdEd2NimLAxYIN8KRsPLo4evp3eqe1Ch8UJi7CSH+Wq0lAbbvdqlMRKko6U3RfwLIHP76ZAPJ4ZLUVLZyCNxcFV/rU/X5l10ANputILQYjq5viD7lS+Jn9gtBuwY2tWJH2ABlqp7K7hCHnFn1nPsyfWjmTjI4ToCpi2eiO1Ku0r1zkpWCEjT3J8CCuKtjdl/+ZWGVggSLuzNGB0yhlc+6YavXuiqUekIcVUXuHX8jForHDNsHMA2ggHPjJOrkfrLJdifl0ly+t+NmKyNuoHj/ZFKCG0Jg0HPcc1D+WiThwQCoRcZ4OlJGy0JE985ziV3CnAh5INis4For88n4wkZsVXwS2pyxZuKUl2O5Szi/dAsMrIGfuAnPmhsUHzo0KLgpWIxtJEXPtorctRDuxGdEJCa8HLaTnusB0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
